/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "./Page.module.css";
import { supabase } from "../utils/supabase";
import WorkoutCard from "./../components/WorkoutCard";

export default function Home({ session }: any) {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    // Fetch the current session and set the user
    const fetchUser = async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession();
      setUser(session?.user);
    };

    fetchUser();
  }, []);

  useEffect(() => {
    if (user) {
      fetchWorkouts();
    }
  }, [user]);

  const fetchWorkouts = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from("workouts")
        .select("*")
        .eq("user_id", user.id);

      if (error) throw error;
      setData(data);
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message);
      } else {
        alert("An unknown error occurred");
      }
    } finally {
      setLoading(false);
    }
  };

  console.log({ user });

  const handleDelete = async (id: string) => {
    try {
      if (!user) return;
      const { data, error } = await supabase
        .from("workouts")
        .delete()
        .eq("id", id)
        .eq("user_id", user.id);
      if (error) throw error;
      fetchWorkouts();
      alert("Workout deleted successfully");
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message);
      } else {
        alert("An unknown error occurred");
      }
    }
  };

  if (user === undefined) {
    return <div className={styles.loading}>Welcome to Workout App.</div>;
  }

  if (loading) {
    return <div className={styles.loading}>Fetching Workouts...</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs x Supabase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        {!user ? (
          <div>
            <p>
              Welcome to Adrenargy. Kindly Login to your account or sign in for
              a demo
            </p>
          </div>
        ) : (
          <div>
            <p className={styles.workoutHeading}>
              Hello <span className={styles.email}>{user.email}</span>, Welcome
              to your dashboard
            </p>
            {data?.length === 0 ? (
              <div className={styles.noWorkout}>
                <p>You have no workouts yet</p>
                <Link href="/create">
                  <button className={styles.button}>
                    Create a New Workout
                  </button>
                </Link>
              </div>
            ) : (
              <div>
                <p className={styles.workoutHeading}>Here are your workouts</p>
                <WorkoutCard data={data} handleDelete={handleDelete} />
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
